    # statモジュールでAnsibleホスト上のアップデートファイルの情報を取得し、変数resultに格納
    - name: get local firmware file size
      stat:
        path: "{{ local_firm_path }}{{ firm_filename }}"
      register: result
      delegate_to: localhost

    # show flashを実行し、表示結果を変数result_show_flashに格納
    - name: get show flash result
      ax_command:
        commands:
          - show flash
      register: result_show_flash

    # show flash表示結果をパースし、ネットワーク機器のディスク容量情報を抽出
    - name: get network device free space
      set_fact:
        flash_free: "{{ result_show_flash.stdout[0] | parse_cli_textfsm( template_show_flash ) }}"

    # ネットワーク機器の空きディスク容量がアップデートファイルよりも小さい場合、fail
    - name: assert if network device's free space is lower than firmware filesize
      assert:
        that:
          - "{{ flash_free[0].FREE_BYTE|regex_replace(',') }} > result.stat.size/1024"
          - "{{ flash_free[1].FREE_BYTE|regex_replace(',') }} > result.stat.size/1024"

    # ネットワーク機器にアップデートファイルを転送する
    # スタックの場合、マスタスイッチ上のflashに格納
    - name: transfer firmware to network device
      net_put:
        src: "{{ local_firm_path }}{{ firm_filename }}"
        dest: "{{ remote_firm_path }}k.img"
        protocol: scp
