    # スタティック経路の追加
    - name: configure static route
      ax_config:
        lines:
          - "ip route {{ item.prefix }} {{ item.mask }} {{ item.nexthop }} poll"
        save_when: modified
      with_items: "{{ static_route }}"
