- name: Change {{  ansible_user }} password
  hosts: all
  gather_facts: no
  connection: network_cli
  max_fail_percentage: 0

  # パスワードを変更・変更後のパスワードを確認するPlaybook
  # パスワードを変更するPlay部分

  tasks:
    # パスワードを変更するタスクの呼び出し
    - name: Call change password tasks
      include_tasks: task_lib/tasklib_change_password.yml


- name: Check new password using AX modules
  hosts: all
  gather_facts: no
  connection: network_cli
  max_fail_percentage: 0

  vars:
    ansible_password: "{{ new_password }}"

  # 期待通りに新パスワードに変更したかを確認するPlay部分

  tasks:
    # ax_factsモジュールを使って新パスワードが変わったかを確認
    # このタスクが失敗した場合、何かしらの要因でパスワードが期待通りに変更されていない
    - name: If this task failed, the password was not changed correctly.
      ax_facts:
        gather_subset:
          - "hardware"
