    # VNIを作成
    - name: configuer "vxlan-vni <vni> in vlan <vid>" 
      ax_config:
        lines:
            - "vxlan-vni {{ vni }}"
        parents: "vlan {{ vid }}"
    
    # VTEPにVNIを追加
    - name: configuer "member vni add <vin> in <vtep>"
      ax_config:
        lines:
           - "member vni add {{ vni }}"
        parents: "interface vxlan {{ vtep }}"  
