    # パスワードを変更
    # アルファベットのみのパスワードとする場合、パスワードが弱いことを注意され、期待通りに動作しないため注意
    # その場合は、コメントアウトしている部分のコメントを外せばOK
    - name: Change password
      cli_command:
        command: "password {{ ansible_user }}"
        check_all: yes
        prompt:
          - "New password:"
#          - "New password:"
          - "Retype new password:"
        answer:
          - "{{ new_password }}"
#          - "{{ new_password }}"
          - "{{ new_password }}"
